[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
#   [entryPoints.https.tls]
  [entryPoints.udpdns]
  address = ":53/udp"
  [entryPoints.dns]
  address = ":53"


#[[tls]]
#  entryPoints = ["https"]
#  [tls.certificate]
#    certFile = "/etc/certs/wildcard_tsunamirr_traefik_me.crt"
#    keyFile = "/etc/certs/wildcard_tsunamirr_traefik_me.key"


[api]

[log]
  level = "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  format = "common"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"

[providers.file]
  filename = "/etc/traefik/services.toml"
